apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: sumo-otelcol-logs-collector
  name: sumo-otelcol-logs-collector
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sumo-otelcol-logs-collector
  labels:
    app.kubernetes.io/name: sumo-otelcol-logs-collector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sumo-otelcol-logs-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sumo-otelcol-logs-collector
    spec:
      containers:
      - args:
        - --config=/etc/otelcol/otelcol-config.yaml
        image: otel/opentelemetry-collector-contrib:0.37.1
        name: otelcol
        imagePullPolicy: IfNotPresent
        # securityContext:
        #   privileged: true
        volumeMounts:
        - mountPath: /etc/otelcol
          name: otelcol-config
        - mountPath: /var/log/pods
          name: varlogpods
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: otelcol-config.yaml
            path: otelcol-config.yaml
          name: sumo-otelcol-logs-collector-configmap
        name: otelcol-config
      - hostPath:
          path: /var/log/pods
          type: ""
        name: varlogpods
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      serviceAccountName: sumo-otelcol-logs-collector
